kind: project
metadata:
  name: test-clone-2
  created: '2022-09-21T12:22:16.741000'
spec:
  functions:
  - url: func.py
    image: mlrun/mlrun
    kind: job
    handler: func
    name: add-2
  workflows:
  - path: workflow.py
    name: testing
    schedule: '*/10 * * * *'
  artifacts: []
  source: git://github.com/GiladShapira94/test.git
  origin_url: git://github.com/GiladShapira94/test.git
  load_source_on_run: false
  desired_state: online
