kind: project
metadata:
  name: schedule-admin
  created: '2022-12-14T11:50:09.753000'
spec:
  functions:
  - url: func.py
    name: add-2
    kind: job
    image: mlrun/mlrun
    handler: func
  workflows:
  - path: workflow.py
    name: testing
    schedule: '*/10 * * * *'
  artifacts: []
  source: git://github.com/GiladShapira94/test.git#refs/heads/master
  origin_url: git://github.com/GiladShapira94/test.git#refs/heads/master
  load_source_on_run: false
  desired_state: online
