kind: project
metadata:
  name: testing-shapira
  created: '2023-04-27T09:49:57.799000'
spec:
  functions:
  - name: serving-test
    handler: function-serving.yaml
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/GiladShapira94/test.git#refs/heads/master
  load_source_on_run: true
  desired_state: online
  owner: shapira
status:
  state: online
